import { screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from 'vitest';
import { renderWithProviders } from '@/shared/test/render-with-providers';
import { server } from '@/mocks/server';
import { setPatientVerified } from '@/mocks/patient-store';
import { addDoctorException, resetSchedulingStore } from '@/mocks/scheduling-store';

import { BookingFlow } from './booking-flow';

const pushMock = vi.fn();

vi.mock('next/navigation', () => ({
  useRouter: () => ({ push: pushMock, replace: vi.fn(), refresh: vi.fn(), back: vi.fn(), forward: vi.fn() }),
  usePathname: () => '/patient/appointments/book',
  useParams: () => ({ locale: 'en' }),
  useSearchParams: () => new URLSearchParams(),
  redirect: vi.fn(),
  permanentRedirect: vi.fn(),
  RedirectType: { push: 'push', replace: 'replace' },
}));

const DOCTOR_ID = 'doctor-profile-1';

/** Matches `resolve-day.ts`'s own local-date `toDateKey` format exactly. */
function todayDateKey(): string {
  const date = new Date();
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
}

beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
afterEach(() => {
  server.resetHandlers();
  resetSchedulingStore();
  pushMock.mockClear();
});
afterAll(() => server.close());

function findSlotButton() {
  const excludedNames = ['Today', 'Previous day', 'Next day'];
  return screen
    .queryAllByRole('button')
    .find((button) => !excludedNames.includes(button.getAttribute('aria-label') ?? button.textContent ?? ''));
}

describe('BookingFlow', () => {
  // Onboarding Redesign integration-gap closure (2026-07-25): every slot
  // rendered here comes from the real, MSW-backed
  // GET /doctors/:id/availability-windows contract (materialized from the
  // seeded demo doctor's own real working hours), never generated by this
  // component itself. An `extra-hours` exception for today guarantees at
  // least one bookable slot regardless of which real weekday this suite
  // happens to run on, without faking the system clock (which would also
  // have to fool MSW's own async request handling).
  it('books a real slot end to end and redirects to Patient Appointments', async () => {
    addDoctorException({ date: todayDateKey(), type: 'extra-hours', hours: { start: '00:00', end: '23:30' } });
    setPatientVerified(true);
    renderWithProviders(<BookingFlow doctorId={DOCTOR_ID} />);

    const slotButton = await vi.waitFor(() => {
      const slot = findSlotButton();
      if (!slot) throw new Error('no slot yet');
      return slot;
    });
    await userEvent.click(slotButton);

    expect(await screen.findByText('Review')).toBeInTheDocument();
    await userEvent.click(screen.getByRole('button', { name: 'Confirm booking' }));

    await vi.waitFor(() => expect(pushMock).toHaveBeenCalledWith('/en/patient/appointments'));
  });

  it('shows the identity-verification gate instead of confirming when the patient is unverified', async () => {
    addDoctorException({ date: todayDateKey(), type: 'extra-hours', hours: { start: '00:00', end: '23:30' } });
    setPatientVerified(false);
    renderWithProviders(<BookingFlow doctorId={DOCTOR_ID} />);

    const slotButton = await vi.waitFor(() => {
      const slot = findSlotButton();
      if (!slot) throw new Error('no slot yet');
      return slot;
    });
    await userEvent.click(slotButton);

    await userEvent.click(await screen.findByRole('button', { name: 'Confirm booking' }));

    expect(await screen.findByText('Verify your identity to book an appointment')).toBeInTheDocument();
    expect(screen.getByRole('link', { name: 'Start verification' })).toBeInTheDocument();
  });

  it('shows an honest empty state when the doctor has marked today unavailable', async () => {
    addDoctorException({ date: todayDateKey(), type: 'unavailable' });
    setPatientVerified(true);
    renderWithProviders(<BookingFlow doctorId={DOCTOR_ID} />);

    expect(await screen.findByText('No slots available on this date')).toBeInTheDocument();
    expect(screen.getByText('Try another date.')).toBeInTheDocument();
    expect(findSlotButton()).toBeUndefined();
  });
});
